apiVersion: v1
kind: Pod
metadata:
  name: service-pod
  labels:
    app: stock-interval-service
spec:
  containers:
  - name: service-container
    image: service-stock:0.0.1
    ports:
    - containerPort: 8080          
