apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    app: service                # Matches the label in the Pod definition
  ports:
  - protocol: TCP
    port: 80                       # Port exposed by the Service
    targetPort: 8080               # Port exposed by the container (defined in the Pod)
  type: ClusterIP                  # Options: ClusterIP, NodePort, LoadBalancer
