apiVersion: v1
kind: Service
metadata:
  name: stock-interval-service
spec:
  selector:
    app: stock-interval-service                
  ports:
  - protocol: TCP
    port: 80                       
    targetPort: 8080               
  type: ClusterIP                  
